/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ninja.seppli.umlgenerator.gradle;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

/**
 * A simple 'hello world' plugin.
 */
public class UmlGeneratorGradlePluginPlugin implements Plugin<Project> {
    public void apply(Project project) {
        project.getExtensions().create("mermaidGenerator", UmlGeneratorExtension.class);
        project.getTasks().create("generateUml", UmlGeneratorTask.class);
    }
}
